changed line 347 from cmap = cm.get_cmap(base_cmap, max(len(all_files), 2)) to cmap = plt.get_cmap(base_cmap, max(len(all_files), 2)) due to error AttributeError: module 'matplotlib.cm' has no attribute 'get_cmap'